# Generated by Django 5.1.1 on 2024-10-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last name')),
                ('phone', models.CharField(max_length=10, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=277, verbose_name='Email Address')),
                ('address', models.TextField(max_length=100, verbose_name='Address')),
            ],
        ),
    ]
